[project]
name = "fine-tune-llama2-7b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.2.0",
    "ipykernel>=7.0.1",
    "jupyter>=1.1.1",
    "polars>=1.34.0",
]
